### PR TITLE
added vain and weak

### PR DESCRIPTION
**Pull request by starryburst**
~~currently not working, can't figure out what is wrong, would be grateful if someone looked at it~~

### CODE REVIEW

**Comment by pikulet** [comment]
@R9H9 you can edit this PR as you see fit

I agree that the term Suspect is confusing

**Comment by starryburst** [comment]
> Also, can I suggest renaming **Suspect** to **Vain** or something to avoid confusion with the EM role?

Yep thats fine!

**Comment by starryburst** [comment]
> ```js
> const Card = require("../../Card");
> const { PRIORITY_KILL_DEFAULT } = require("../../const/Priority");
> 
> module.exports = class Weak extends Card {
>   constructor(role) {
>     super(role);
> 
>     this.actions = [
>       {
>         priority: PRIORITY_KILL_DEFAULT,
>         labels: ["block", "hidden"],
>         run: function () {
>           if (this.game.getStateName() != "Night") return;
> 
>           if (!this.actor.alive) return;
> 
>           for (let action of this.game.actions[0]) {
>             if (action.actor == this.actor && !action.hasLabel("hidden")) {
>               if (action.actor.role.alignment !== action.target.role.alignment) {
>                 if (this.dominates()) this.target.kill("otherAlignment", this.actor);
>               }
>             }
>           }
>         },
>       },
>     ];
>   }
> };
> ```
> 
> ```js
> const Card = require("../../Card");
> const { PRIORITY_KILL_DEFAULT } = require("../../const/Priority");
> 
> module.exports = class Suspect extends Card {
>   constructor(role) {
>     super(role);
> 
>     this.actions = [
>       {
>         priority: PRIORITY_KILL_DEFAULT,
>         labels: ["block", "hidden"],
>         run: function () {
>           if (this.game.getStateName() != "Night") return;
> 
>           if (!this.actor.alive) return;
> 
>           for (let action of this.game.actions[0]) {
>             if (action.actor == this.actor && !action.hasLabel("hidden")) {
>               if (action.actor.role.alignment === action.target.role.alignment) {
>                 if (this.dominates()) this.target.kill("otherAlignment", this.actor);
>               }
>             }
>           }
>         },
>       },
>     ];
>   }
> };
> ```

It still breaks after doing this

**Comment by starryburst** [comment]
I'm having trouble resolving the merge conflicts, I resolved them on local but for some reason its not appearing here?

**Pull request merged**
