### PR TITLE
feat: ghoul role

### PR DESCRIPTION
**Pull request by Golbolco**
Ghoul role per Ruviz's role suggestion document

It's a Cult-sided Monkey that can only "monkey see" from dead players

### CODE REVIEW

**Comment by pikulet** [comment]
@Golbolco ghoul will only be able to copy dead roles with dead actions, like vengeful spirit. won't be able to copy dead cop to check alive.

**Comment by Golbolco** [comment]
> @Golbolco ghoul will only be able to copy dead roles with dead actions, like vengeful spirit. won't be able to copy dead cop to check alive.

uh oh that is not fun, will work on

**Comment by Golbolco** [comment]
> @Golbolco ghoul will only be able to copy dead roles with dead actions, like vengeful spirit. won't be able to copy dead cop to check alive.

Looking at this again: would you recommend using data to achieve the intended effect?

**Comment by pikulet** [comment]
the fix is nontrivial. Monkey only copies actions someone was going to do, but what's happening here is that you want to copy an action that wasn't going to happen.

You also have to consider the problematic treatment of copying these types of roles
1. Inventor. The code explicitly checks for actor.alive in the run function 
2. Justice. You must map the target the correct number of times.

**Comment by Golbolco** [comment]
> the fix is nontrivial. Monkey only copies actions someone was going to do, but what's happening here is that you want to copy an action that wasn't going to happen.
> 
> You also have to consider the problematic treatment of copying these types of roles
> 
> 1. Inventor. The code explicitly checks for actor.alive in the run function
> 2. Justice. You must map the target the correct number of times.

for those last two: if Ghoul can only copy active power roles, I'm ok with that. leave passive and reflexive roles alone, it sucks but it's much more work to do

**Comment by pikulet** [comment]
with the way you implemented it, ghoul
- can copy Vengeful spirit
- cannot copy cop
- cannot copy dreamer

**Pull request closed without merging**
