### PR TITLE
fix: polar bears meet and vote together

### PR DESCRIPTION
**Pull request by Golbolco**
title

### CODE REVIEW

**Comment by pikulet** [comment]
multiactor multimeeting has a bug that needs to be fixed in Games/core, it's the same as what you raised in discord.

it won't wait for the second person to vote

**Comment by Golbolco** [comment]
damn. that really sucks. but ok

**Comment by pikulet** [comment]
It's good thing, we can use polar bear to test that functionality and open up for future multiActor multimeeting roles

**Comment by pikulet** [comment]
@Golbolco can you give more details on how to resolve votes for multi actor multi meeting?

A chooses 1 and 2
B chooses 1 and 3

what should the result be?

**Comment by Golbolco** [comment]
> @Golbolco can you give more details on how to resolve votes for multi actor multi meeting?
> 
> A chooses 1 and 2 B chooses 1 and 3
> 
> what should the result be?

answered on discord, can post here for clarity

**Pull request closed without merging**
