### PR TITLE
feat: don role

### PR DESCRIPTION
**Pull request by Golbolco**
second attempt at don, this is just a draft since last time didn't work but let's go ahead and find out

this time I just added a shouldMeet function that cancels the overturn vote if the target is mafia

### CODE REVIEW

**Comment by pikulet** [comment]
before writing the code, you should state the intended interaction with

1. multiple don
2. don + gov

**Comment by Golbolco** [comment]
> before writing the code, you should state the intended interaction with
> 
> 1. multiple don

Should work the same as multiple govs. We played several games today with multiple (3) govs, and it works as a group meeting so the Govs have to vote with majority for their OT to go through. I don't plan on making any changes to this part of the code

> 2. don + gov

the only issue I foresee here is that Dons should not be able to OT if the vote is on a mafioso. Thus my code intends to exclude them from the OT if the Village vote was on a Mafia player. Otherwise, it should work exactly like if there were multiple govs

**Comment by pikulet** [comment]
don + gov interaction --> if the vote is on a villager, don chooses to OT to person A and gov chooses to OT to person B

what's the result

**Comment by Golbolco** [comment]
> don + gov interaction --> if the vote is on a villager, don chooses to OT to person A and gov chooses to OT to person B
> 
> what's the result

no OT, the game should default to condemning the villager

**Pull request closed without merging**
